name: Deploy to GitHub Pages
on: 
  push:
    branches: [master]
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.2.1
        with:
          dotnet-version: 5.0
      - name: Publish .NET Core Project
        run: dotnet publish ExpenceTracker.csproj -c Release -o release --nologo
